version: '2.1'

networks:
    explorer_lan:
        name: explorer_lan
        driver: bridge

services:
  # Explorer Postgres DB
  explorer_db:
    image: postgres:10.6
    restart: always
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
    volumes:
      - ./volumes/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - explorer_lan
    ports:
      - ${BLOCKSCOUT_POSTGRESQL_PORT}:5432
    expose:
      - ${BLOCKSCOUT_POSTGRESQL_PORT}

  # Blockchain Explorer
  explorer:
    build:
      context: ./blockexplorer
      dockerfile: docker/Dockerfile
      args:
        SECRET_KEY_BASE: ${BLOCKSCOUT_SECRET_KEY_BASE}
        COIN_NAME: ${BLOCKSCOUT_COIN_NAME}
    restart: always
    volumes:
      - ./blockexplorer:/app
    environment:
      - SUBNETWORK=SEED-Testnet
      - LOGO=/images/seed-logo.svg
      - LOGO_FOOTER=/images/seed-footer-logo.svg
      - ETHEREUM_JSONRPC_VARIANT=parity
      - COIN=
      - SECRET_KEY_BASE=${BLOCKSCOUT_SECRET_KEY_BASE}
      - ETHEREUM_JSONRPC_HTTP_URL=http://172.17.0.1:${PARITY_JSON_RPC_PORT}
      - ETHEREUM_JSONRPC_TRACE_URL=http://172.17.0.1:${PARITY_JSON_RPC_PORT}
      - ETHEREUM_JSONRPC_WS_URL=ws://172.17.0.1:${PARITY_WEB_SOCKETS_PORT}
      - DATABASE_URL=postgresql://postgres:postgres@explorer_db:5432/explorer?ssl=false
    networks:
      - explorer_lan 
    ports:
      - ${BLOCKSCOUT_PORT}:4000
    expose:
      - ${BLOCKSCOUT_PORT}
    depends_on:
      - explorer_db
    command:
      - ./run.sh
